import {
  Profile,
  ResearchArea,
  Publication,
  News,
  Seminar,
  Conference,
  Achievement,
  GalleryAlbum,
  Collaborator,
  ContactInfo,
} from "./types";
import { getImageUrl } from "./cloudinary";

export const profileData: Profile = {
  name: "Prof. Rabian Wangkeeree",
  title: "Professor of Mathematics",
  position: "Director of the Research Center for Academic Excellence in Mathematics",
  institution: "Naresuan University, Thailand",
  bio: [
    "I am a Full Professor at the Department of Mathematics, Faculty of Science, Naresuan University, Thailand, where I have been advancing mathematical research and education since 2002.",
    "My research bridges advanced mathematics with cutting-edge artificial intelligence, focusing on fixed point theory, machine learning algorithms, and optimization methods. I specialize in developing novel optimizers and deep learning architectures grounded in rigorous mathematical foundations.",
    "My work translates theoretical advances into real-world AI applications, particularly in medical imaging AI (automated diagnosis, glaucoma detection, pneumonia classification) and energy AI (smart grid optimization, renewable energy systems). I am passionate about creating algorithms that not only push the boundaries of mathematical understanding but also solve critical challenges in healthcare and sustainable energy.",
    "As Director of the Research Center for Academic Excellence in Mathematics at Naresuan University, I lead interdisciplinary research initiatives and mentor the next generation of researchers at the intersection of mathematics, machine learning, and AI applications."
  ],
  avatarUrl: getImageUrl("/images/profile/photo1.jpg"), // Real photo from assets
  socials: {
    scopus: "https://www.scopus.com/authid/detail.uri?authorId=9335162000",
    googleScholar: "https://scholar.google.com/citations?user=ZbqhBi0AAAAJ&hl=th",
    mathGenealogy: "https://www.mathgenealogy.org/id.php?id=126415",
    email: "mailto:rabianw@nu.ac.th",
  },
  impactStats: {
    publications: 150,
    yearsExperience: 23,
    awards: 10,
  },
};

export const researchAreasData: ResearchArea[] = [
  {
    id: "ml-dl",
    title: "Machine Learning & Deep Learning",
    description: "Developing novel algorithms for Support Vector Machines, Neural Networks, and Deep Learning architectures with applications in medical imaging and classification.",
    topics: ["Support Vector Machines", "Convolutional Neural Networks", "Variational Autoencoders", "PyTorch & TensorFlow"],
    iconName: "BrainCircuit",
  },
  {
    id: "opt-theory",
    title: "Optimization Theory",
    description: "Advanced research in convex optimization, robust optimization, and optimality conditions for complex mathematical programming problems.",
    topics: ["Convex Optimization", "Robust Optimization", "Semidefinite Programming", "Approximation Theory"],
    iconName: "LineChart",
  },
  {
    id: "fixed-point",
    title: "Fixed Point Theory",
    description: "Theoretical and computational aspects of fixed point theory with applications to equilibrium problems and variational inequalities.",
    topics: ["Equilibrium Problems", "Variational Inequalities", "Iterative Methods", "CAT(0) Spaces"],
    iconName: "Target",
  },
  {
    id: "comp-methods",
    title: "Computational Methods",
    description: "Implementation of algorithms and development of computational tools for solving complex optimization and machine learning problems.",
    topics: ["Python Programming", "R Statistical Computing", "Algorithm Development", "Scientific Computing"],
    iconName: "Code",
  },
];

export const publicationsData: Publication[] = [
  {
    id: "pub-2026-cjm-111333",
    title: "Multi-view Laplacian twin support vector machine with pinball loss function",
    authors: "Vipavee Damminsed & Rabian Wangkeeree",
    journal: "Carpathian Journal of Mathematics — Accepted, In Press",
    date: "2026",
    link: "https://www.carpathian.cunbm.utcluj.ro/all-issues-archive/",
    featured: true,
  },
  {
    id: "pub-2026-rico-100742",
    title: "A Neurodynamical Neural Network Approach for Solving Support Vector Machine Problems with Generalized Pinball Loss Functions via Hyperbolic Tangent Smoothing Technique",
    authors: "Rattanaporn Wangkeeree, Rabian Wangkeeree, Yirga Abebe Belay, & Kasamsuk Ungchittrakool",
    journal: "Results in Control and Optimization (Elsevier) — Accepted, In Press",
    date: "2026",
    link: "https://authors.elsevier.com/tracking/article/details.do?aid=100742&jid=RICO&surname=Wangkeeree",
    featured: true,
  },
  {
    id: "pub-2026-sym-782",
    title: "Inertial Forward–Backward–Forward Algorithm with Moving Point Projection for Monotone Inclusions and Image Restoration",
    authors: "Thammasiri, P., Berinde, V., Plubtieng, S., Ungchittrakool, K., & Wangkeeree, R.",
    journal: "Symmetry (MDPI), Vol. 18, Issue 5, 782",
    date: "2026",
    doi: "10.3390/sym18050782",
    link: "https://doi.org/10.3390/sym18050782",
    featured: false,
  },
  {
    id: "pub-2026-1",
    title: "A relaxed iterative method for approximating solutions of pseudomonotone hierarchical variational inequality problems in Hilbert spaces",
    authors: "Gebremeskel, Kibrom Gebrehiwot, Tewele, Teklebrhan Guesh, Wangkeeree, Rabian, Belay, Yirga Abebe, & Meche, Tesfalem Hadush",
    journal: "The Journal of Analysis (Springer), 08 May 2026",
    date: "2026",
    doi: "10.1007/s41478-026-01096-8",
    link: "https://link.springer.com/article/10.1007/s41478-026-01096-8",
    featured: true,
  },
  {
    id: "pub-2026-2",
    title: "Neurodynamical Neural Network Method for Solving Support Vector Machines with Epigraph Reformulated Generalized Pinball Loss Function",
    authors: "Wangkeeree, R., Wangkeeree, R., Belay, Y.A., Ungchittrakool, K., & Nazemi, A.",
    journal: "Journal of Computational and Applied Mathematics (Elsevier), Article 117754, 2026",
    date: "2026",
    doi: "10.1016/j.cam.2026.117754",
    link: "https://www.sciencedirect.com/science/article/pii/S0377042726003961",
    featured: true,
  },
  {
    id: "pub-2026-3",
    title: "A Projection Neural Network With Delays and Optimization Approaches for Solving Absolute Value Equations",
    authors: "Prathom, Kiattisak, Wangkeeree, Rabian, Belay, Yirga A., & Hongsri, Arthit",
    journal: "IEEE Access, Vol. 14, pp. 50141–50155, March 2026",
    date: "2026",
    doi: "10.1109/ACCESS.2026.3679347",
    link: "https://ieeexplore.ieee.org/document/11458726",
    featured: true,
  },
  {
    id: "pub-2026-4",
    title: "Continuity and Lipschitz Properties of Approximate Weak Solution Maps via Nonlinear Scalarization",
    authors: "Preechasilp, P. & Wangkeeree, R.",
    journal: "Carpathian Journal of Mathematics, Issue 4/2026 — Accepted, In Press (Special Issue: AMC-2025)",
    date: "2026",
    featured: true,
  },
  {
    id: "pub-2026-5",
    title: "Multi-view machine learning with an optic disc localization for glaucoma diagnosis",
    authors: "Siying, Parichat, Muangphara, Thitima, Photun, Aphinan, Suppalap, Siwakon, Klinsuwan, Thitiphat, Phruancharoen, Chatmongkol, Treeyawedkul, Sirinan, Chira-adisai, Tanate, Supattanawong, Ying, & Wangkeeree, R.",
    journal: "Applied Sciences (MDPI) — Accepted, In Press",
    date: "2026",
    featured: true,
  },
  {
    id: "pub-2026-6",
    title: "A Projection Recurrent Neural Network Method for Solving Absolute Value Equations Associated with Second-Order Cones",
    authors: "Wangkeeree, R., Wangkeeree, R., Nazemi, A., Belay, Y.A., & Ungchittrakool, K.",
    journal: "Journal of Computational and Applied Mathematics (Elsevier), Vol. 485, 15 October 2026, 117567",
    date: "2026",
    link: "https://www.sciencedirect.com/science/article/abs/pii/S0377042726002153",
    featured: false,
  },
  {
    id: "pub-2026-7",
    title: "A Discriminative Correlation Platform for Feature Representation Learning in Multimodal Information Computing",
    authors: "Gao, Lei, Liu, Kai, Hong, Phuoc-Thanh, Termritthikun, Chakkrit, Luangsawang, Kanin, Wangkeeree, R., Muneesawang, Paisarn, Hnoohom, Narit, & Guan, Ling",
    journal: "ACM Transactions on Multimedia Computing, Communications, and Applications (TOMM) — March 2026",
    date: "2026",
    doi: "10.1145/3787857",
    link: "https://doi.org/10.1145/3787857",
    featured: false,
  },
  {
    id: "pub-2026-8",
    title: "Efficient Large-Scale Classification with Linex Least Square Twin Bounded Support Vector Machine",
    authors: "Wangkeeree, R., Makmuang, D., & Wangkeeree, R.",
    journal: "Carpathian Journal of Mathematics, Vol. 42(2), pp. 287-317",
    date: "2026",
    doi: "10.37193/CJM.2026.02.06",
    link: "https://www.carpathian.cunbm.utcluj.ro/article/efficient-large-scale-classification-with-linex-least-square-twin-bounded-support-vector-machine/",
    featured: false,
  },
  {
    id: "pub-2025-9",
    title: "A Halpern Method for Solving Perturbed Double Inertial Krasnoselskii-Mann Iterations with Applications to Image Restoration Problems",
    authors: "Rattanaporn Wangkeeree, Rabian Wangkeeree, Yirga Abebe Belay, Kasamsuk Ungchittrakool, Purit Thammasiri, and Pakkaporn Preechasilp",
    journal: "Bangmod International Journal of Mathematical & Computational Science, Vol. 11 (2025)",
    date: "2025",
    doi: "10.58715/bangmodjmcs.2025.11.16",
    link: "https://bangmodjmcs.com/index.php/bangmodmcs/article/view/209",
    featured: false,
  },
  {
    id: "pub-2025-10",
    title: "Regularized Nesterov's Accelerated Damped BFGS Method for Stochastic Optimization",
    authors: "Suppalap, S. and Makmuang, D. and Damminsed, V. and Wangkeeree, R.",
    journal: "Journal of Computational and Applied Mathematics, Vol. 467, pp. 116616",
    date: "2025",
    featured: false,
  },
  {
    id: "pub-2025-11",
    title: "Necessary Conditions to e-Quasi Solutions and e-Generalized KKT Conditions for Non-Lipschitzian Optimization Problems",
    authors: "Wangkeeree, R., Kerdkaew, J., Lee, G.M., Wangkeeree, R., & Sisarat, N.",
    journal: "Journal of Nonlinear and Convex Analysis, Vol. 26, No. 10, pp. 2843–2858",
    date: "2025",
    featured: false,
  },
  {
    id: "pub-2025-12",
    title: "Automated Optic Disc and Cup Segmentation Using Mask R-CNN for Glaucoma Assessment",
    authors: "Inkong-Ngam, S. and Tamee, K. and Wangkeeree, R.",
    journal: "International Conference on Cybernetics and Innovations ICCI 2025, 2025",
    date: "2025",
    featured: false,
  },
  {
    id: "pub-2025-13",
    title: "Smooth Support Vector Machine with Rescaled Generalized Pinball Loss for Classification",
    authors: "Suppalap, Siwakon, Makmuang, Dawrawee, Damminsred, Vipavee, & Wangkeeree, R.",
    journal: "Journal of Supercomputing, Vol. 81, No. 1, pp. 217",
    date: "2025",
    link: "https://doi.org/10.1007/s11227-024-06697-3",
    featured: false,
  },
  {
    id: "pub-2024-14",
    title: "Robust Support Vector Machine With Asymmetric Truncated Generalized Pinball Loss",
    authors: "Suppalap, Siwakon & Wangkeeree, R.",
    journal: "IEEE Access, Vol. 12, pp. 155696–155717",
    date: "2024",
    link: "https://doi.org/10.1109/ACCESS.2024.3485214",
    featured: false,
  },
  {
    id: "pub-2024-15",
    title: "Improved Generalized-Pinball-Loss-Based Laplacian Twin Support Vector Machine for Data Classification",
    authors: "Damminsred, Vipavee & Wangkeeree, R.",
    journal: "Symmetry, Vol. 16, No. 10, pp. 1373",
    date: "2024",
    link: "https://doi.org/10.3390/sym16101373",
    featured: false,
  },
  {
    id: "pub-2024-16",
    title: "Performance Evaluation of Thailand's 8 MW Wind Farm Feeder Trip, Energy Generation, and Loss Using 5 MWh BESS - A Statistical and Economic Approach",
    authors: "Ngoenmeesri, R., Chindaruksa, S., Wangkeeree, R., & Sirisamphanwong, C.",
    journal: "IEEE Access, Vol. 12, pp. 73620–73632",
    date: "2024",
    featured: false,
  },
  {
    id: "pub-2024-17",
    title: "Characterizations of ε-Approximate Solutions for Robust Convex Semidefinite Programming Problems",
    authors: "Wangkeeree, R. and Preechasilp, P.",
    journal: "Carpathian Journal of Mathematics, Vol. 40, No. 2, pp. 493–513",
    date: "2024",
    featured: false,
  },
  {
    id: "pub-2024-18",
    title: "Necessary and Sufficient Optimality Conditions for Reverse Quasiconvex Programs",
    authors: "Sisarat, N. & Wangkeeree, R.",
    journal: "Carpathian Journal of Mathematics, Vol. 40, No. 2, pp. 431–442",
    date: "2024",
    featured: false,
  },
  {
    id: "pub-2023-19",
    title: "A Novel Support Vector Machine with Generalized Pinball Loss for Uncertain Data Classification",
    authors: "Damminsed, V., Panup, W., Makmuang, D., Suppalap, S., & Wangkeeree, R.",
    journal: "Mathematical Methods in the Applied Sciences, Vol. 46, No. 18, pp. 18729–18748",
    date: "2023",
    featured: false,
  },
  {
    id: "pub-2023-20",
    title: "Power Quality Enhancement for Thailand's Wind Farm Using 5 MWh Li-ion Battery Energy Storage System",
    authors: "Ngoenmeesri, R., Chidaruksa, S., Wangkeeree, R., & Sirisamphanwong, C.",
    journal: "Heliyon, Vol. 9, No. 11, pp. e22029",
    date: "2023",
    featured: false,
  },
  {
    id: "pub-2023-21",
    title: "The Regularized Stochastic Nesterov's Accelerated Quasi-Newton Method with Applications",
    authors: "Makmuang, D., Suppalap, S., & Wangkeeree, R.",
    journal: "Journal of Computational and Applied Mathematics, Vol. 428, pp. 115190",
    date: "2023",
    featured: false,
  },
  {
    id: "pub-2023-22",
    title: "Smooth Support Vector Machine with Generalized Pinball Loss for Pattern Classification",
    authors: "Makmuang, D., Ratiphaphongthon, W., & Wangkeeree, R.",
    journal: "Journal of Supercomputing, Vol. 79, No. 11, pp. 11684–11706",
    date: "2023",
    featured: false,
  },
  {
    id: "pub-2023-23",
    title: "Evaluation of Machine Learning Algorithms for Supervised Anomaly Detection and Comparison Between Static and Dynamic Thresholds in Photovoltaic Systems",
    authors: "Klinsuwan, T., Ratiphaphongthon, W., Wangkeeree, R., Wangkeeree, R., & Sirisamphanwong, C.",
    journal: "Energies, Vol. 16, No. 4, pp. 1947",
    date: "2023",
    featured: false,
  },
  {
    id: "pub-2023-24",
    title: "Strong Duality in Parametric Robust Semi-Definite Linear Programming and Exact Relaxations",
    authors: "Sisarat, N., Wangkeeree, R., & Wangkeeree, R.",
    journal: "Carpathian Journal of Mathematics, Vol. 39, No. 2, pp. 477–490",
    date: "2023",
    featured: false,
  },
  {
    id: "pub-2023-25",
    title: "Laplacian Twin Support Vector Machine with Pinball Loss for Semi-Supervised Classification",
    authors: "Damminsed, V., Panup, W., & Wangkeeree, R.",
    journal: "IEEE Access, Vol. 11, pp. 31399–31416",
    date: "2023",
    featured: false,
  },
  {
    id: "pub-2023-26",
    title: "An Improved Technique for Pneumonia Infected Patients Image Recognition Based on Combination Algorithm of Smooth Generalized Pinball SVM and Variational Autoencoders",
    authors: "Ratiphaphongthon, W., Panup, W., & Wangkeeree, R.",
    journal: "IEEE Access, Vol. 10, pp. 107431–107445",
    date: "2023",
    featured: false,
  },
  {
    id: "pub-2021-27",
    title: "Stochastic Subgradient for Large-Scale Support Vector Machine Using the Generalized Pinball Loss Function",
    authors: "Panup, W. & Wangkeeree, R.",
    journal: "Symmetry, Vol. 13, No. 9, pp. 1652",
    date: "2021",
    featured: false,
  },
  {
    id: "pub-2021-28",
    title: "Approximate Quasi Solutions of Multiobjective Optimization Problems",
    authors: "Khantree, C. & Wangkeeree, R.",
    journal: "Thai Journal of Mathematics, Vol. 19, No. 1, pp. 233–249",
    date: "2021",
    featured: false,
  },
  {
    id: "pub-2021-29",
    title: "Regularized Projection Method of Solving Split System of Fixed Point Set Constraint Equilibrium Problems in Real Hilbert Space",
    authors: "Gebrie, A.G. & Wangkeeree, R.",
    journal: "Fixed Point Theory, Vol. 22, No. 1, pp. 169–188",
    date: "2021",
    featured: false,
  },
  {
    id: "pub-2021-30",
    title: "Levitin-Polyak Well-Posedness by Perturbations of Strong Vector Mixed Quasivariational Inequality Problems",
    authors: "Boonman, P., Anh, L.Q., & Wangkeeree, R.",
    journal: "Journal of Nonlinear and Convex Analysis, Vol. 22, No. 7, pp. 1327–1352",
    date: "2021",
    featured: false,
  },
  {
    id: "pub-2021-31",
    title: "Approximate Optimality and Approximate Duality in Nonsmooth Composite Vector Optimization",
    authors: "Sirichunwijit, T., Wangkeeree, R., & Sisarat, N.",
    journal: "Carpathian Journal of Mathematics, Vol. 37, No. 3, pp. 529–540",
    date: "2021",
    featured: false,
  },
  {
    id: "pub-2021-32",
    title: "Characterizing the Weighted Robust Optimal Solution Sets of Optimization Problem with Data Uncertainty via Dual Approaches",
    authors: "Khantree, C. & Wangkeeree, R.",
    journal: "Journal of Nonlinear and Convex Analysis, Vol. 21, No. 9, pp. 1903–1930",
    date: "2021",
    featured: false,
  },
  {
    id: "pub-2020-33",
    title: "A Novel Twin Parametric Support Vector Machine for Large Scale Problem",
    authors: "Makmuang, D., Wangkeeree, R., Nattee, C., & Khamsemanan, N.",
    journal: "Thai Journal of Mathematics, Vol. 18, No. 4, pp. 2107–2127",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-34",
    title: "An Iterative Scheme for Solving Split System of Minimization Problems",
    authors: "Gebrie, A.G. & Wangkeeree, R.",
    journal: "Journal of Computational Analysis and Applications, Vol. 28, No. 6, pp. 968–980",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-35",
    title: "On Set Containment Characterizations for Sets Described by Set-Valued Maps with Applications",
    authors: "Sisarat, N., Wangkeeree, R., & Lee, G.M.",
    journal: "Journal of Optimization Theory and Applications, Vol. 184, pp. 824–841",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-36",
    title: "Pointwise Well-Posedness and Scalarization for Set Optimization Problems with a Partial Order Relation",
    authors: "Preechasilp, P. & Wangkeeree, R.",
    journal: "Thai Journal of Mathematics, Vol. 18, No. 3, pp. 1623–1638",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-37",
    title: "On Highly Robust Approximate Solutions for Nonsmooth Convex Optimizations with Data Uncertainty",
    authors: "Kerdkaew, J., Wangkeeree, R., & Lee, G.M.",
    journal: "Thai Journal of Mathematics, Vol. 18, No. 3, pp. 977–995",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-38",
    title: "On Optimality Conditions for Robust Weak Sharp Solution in Uncertain Optimizations",
    authors: "Kerdkaew, J., Wangkeeree, R., & Lee, G.M.",
    journal: "Carpathian Journal of Mathematics, Vol. 36, No. 3, pp. 443–452",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-39",
    title: "Proximal Method of Solving Split System of Minimization Problem",
    authors: "Gebrie, A.G. & Wangkeeree, R.",
    journal: "Journal of Applied Mathematics and Computing, Vol. 63, No. 1-2, pp. 107–132",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-40",
    title: "Parallel Proximal Method of Solving Split System of Fixed Point Set Constraint Minimization Problems",
    authors: "Gebrie, A.G. & Wangkeeree, R.",
    journal: "Revista de la Real Academia de Ciencias Exactas, Fisicas y Naturales - Serie A: Matematicas, Vol. 114, No. 1, pp. 13",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-41",
    title: "Well-Posedness for Set Optimization Problems Involving Set Order Relations",
    authors: "Vui, P.T., Anh, L.Q., & Wangkeeree, R.",
    journal: "Acta Mathematica Vietnamica, Vol. 45, No. 8",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-42",
    title: "Sequential Characterization of Approximate Solutions in Convex Vector Optimization Problems with Set-Valued Maps",
    authors: "Sisarat, N., Wangkeeree, R., & Tanaka, T.",
    journal: "Journal of Global Optimization, Vol. 77, No. 2, pp. 273–287",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-43",
    title: "Some Characterizations of Robust Solution Sets for Uncertain Convex Optimization Problems with Locally Lipschitz Inequality Constraints",
    authors: "Sisarat, N., Wangkeeree, R., & Lee, G.M.",
    journal: "Journal of Industrial and Management Optimization, Vol. 16, No. 1, pp. 469–493",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-44",
    title: "Characterizing Robust Weak Sharp Solution Sets of Uncertain Convex Optimizations",
    authors: "Kerdkaew, J. & Wangkeeree, R.",
    journal: "Journal of Industrial and Management Optimization, Vol. 16, No. 6, pp. 2651–2673",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2020-45",
    title: "Characterizing Solution Set of Convex Optimization Problems Without Convexity of Constraints",
    authors: "Sisarat, N. & Wangkeeree, R.",
    journal: "Optimization Letters, Vol. 14, No. 5, pp. 1127–1144",
    date: "2020",
    featured: false,
  },
  {
    id: "pub-2019-46",
    title: "A Note on Semicontinuity of the Solution Mapping for Parametric Set Optimization Problems",
    authors: "Preechasilp, P. & Wangkeeree, R.",
    journal: "Optimization Letters, Vol. 13, No. 5, pp. 1085–1094",
    date: "2019",
    featured: false,
  },
  {
    id: "pub-2019-47",
    title: "Inertial Method for Bilevel Variational Inequality Problems with Fixed Point and Minimizer Point Constraints",
    authors: "Yimer, S.E., Kumam, P., Gebrie, A.G., & Wangkeeree, R.",
    journal: "Mathematics, Vol. 7, No. 9, pp. 841",
    date: "2019",
    featured: false,
  },
  {
    id: "pub-2019-48",
    title: "On Approximate Quasi Solutions for Nonsmooth Robust Semi-Infinite Optimization Problems",
    authors: "Khantree, C. & Wangkeeree, R.",
    journal: "Carpathian Journal of Mathematics, Vol. 35, No. 3, pp. 417–426",
    date: "2019",
    featured: false,
  },
  {
    id: "pub-2019-49",
    title: "Levitin–Polyak Well-Posedness for Set Optimization Problems Involving Set Order Relations",
    authors: "Vui, P.T. and Anh, L.Q. and Wangkeeree, R.",
    journal: "Positivity, Vol. 23, No. 3, pp. 599–616",
    date: "2019",
    featured: false,
  },
  {
    id: "pub-2019-50",
    title: "On the Existence of Solutions of Symmetric Vector Equilibrium Problems via Nonlinear Scalarization",
    authors: "Farajzadeh, A.P., Wangkeeree, R., & Kerdkaew",
    journal: "Bulletin of the Iranian Mathematical Society, Vol. 45, No. 1, pp. 35–58",
    date: "2019",
    featured: false,
  },
  {
    id: "pub-2019-51",
    title: "Sequential Characterization of Robust Optimal Solutions in Uncertain Convex Programs via Perturbation Approach",
    authors: "Sisarat, N., Wangkeeree, R., & Lee, G.M.",
    journal: "Carpathian Journal of Mathematics, Vol. 35, No. 2, pp. 253–262",
    date: "2019",
    featured: false,
  },
  {
    id: "pub-2019-52",
    title: "Necessary and Sufficient KKT Optimality Conditions in Nonconvex Multi-Objective Optimization Problems with Cone Constraints",
    authors: "Sisarat, N. & Wangkeeree, R.",
    journal: "Pacific Journal of Optimization, Vol. 15, No. 3, pp. 477–490",
    date: "2019",
    featured: false,
  },
  {
    id: "pub-2018-53",
    title: "KKT Optimality Conditions in Non-Smooth, Nonconvex Optimization",
    authors: "Sisarat, N., Wangkeeree, R., & Lee, G.M.",
    journal: "Journal of Nonlinear and Convex Analysis, Vol. 19, No. 8, pp. 1319–1329",
    date: "2018",
    featured: false,
  },
  {
    id: "pub-2018-54",
    title: "Levitin-Polyak Well-Posedness for Parametric Quasivariational Inclusion and Disclusion Problems",
    authors: "Boonman, P. & Wangkeeree, R.",
    journal: "Carpathian Journal of Mathematics, Vol. 34, No. 3, pp. 295–303",
    date: "2018",
    featured: false,
  },
  {
    id: "pub-2018-55",
    title: "A Hybrid Subgradient Algorithm for Finding a Common Solution of Pseudomonotone Equilibrium Problems and Hierarchical Fixed Point Problems of Nonexpansive Mappings",
    authors: "Wangkeeree, R., Rattanaseeha, K., & Wangkeeree, R.",
    journal: "Thai Journal of Mathematics, Vol. 16, No. 1, pp. 61–77",
    date: "2018",
    featured: false,
  },
  {
    id: "pub-2018-56",
    title: "The General Iterative Methods for Split Variational Inclusion Problem and Fixed Point Problem in Hilbert Spaces",
    authors: "Wangkeeree, R., Rattanaseeha, K., & Wangkeeree, R.",
    journal: "Journal of Computational Analysis and Applications, Vol. 25, No. 1, pp. 19–31",
    date: "2018",
    featured: false,
  },
  {
    id: "pub-2018-57",
    title: "Levitin-Polyak Well-Posedness for Strong Vector Mixed Quasivariational Inequality Problems",
    authors: "Boonman, P., Wangkeeree, R., & Anh, L.Q.",
    journal: "Thai Journal of Mathematics, Vol. 16, No. 2, pp. 383–399",
    date: "2018",
    featured: false,
  },
  {
    id: "pub-2018-58",
    title: "Parallel Extragradient-Proximal Methods for Solving Split System of Fixed Point Set Constraint Equilibrium Problem in Real Hilbert Space",
    authors: "Gebrie, A.G. & Wangkeeree, R.",
    journal: "Research in Fixed Point Theory and Applications, Vol. 2018",
    date: "2018",
    featured: false,
  },
  {
    id: "pub-2018-59",
    title: "Painlevé–Kuratowski Convergences of the Solution Sets for Generalized Vector Quasi-Equilibrium Problems",
    authors: "Anh, L.Q. and Bantaojai, T. and Hung, N.V. and Tam, V.M. and Wangkeeree, R.",
    journal: "Computational and Applied Mathematics, Vol. 37, No. 3, pp. 3832–3845",
    date: "2018",
    featured: false,
  },
  {
    id: "pub-2018-60",
    title: "Hybrid Projected Subgradient-Proximal Algorithms for Solving Split Equilibrium Problems and Split Common Fixed Point Problems of Nonexpansive Mappings in Hilbert Spaces",
    authors: "Gebrie, A.G. & Wangkeeree, R.",
    journal: "Fixed Point Theory and Applications, Vol. 2018, No. 1, pp. 5",
    date: "2018",
    featured: false,
  },
  {
    id: "pub-2017-61",
    title: "Linesearch Algorithms for Split Generalized Equilibrium Problems and Two Families of Strict Pseudo-Contraction Mappings",
    authors: "Rattanaseeha, K., Wangkeeree, R., & Wangkeeree, R.",
    journal: "Thai Journal of Mathematics, Vol. 15, No. 3, pp. 581–606",
    date: "2017",
    featured: false,
  },
  {
    id: "pub-2017-62",
    title: "Levitin-Polyak Well-Posedness for Lexicographic Vector Equilibrium Problems",
    authors: "Wangkeeree, R. & Bantaojai, T.",
    journal: "Journal of Nonlinear Sciences and Applications, Vol. 10, pp. 354–367",
    date: "2017",
    featured: false,
  },
  {
    id: "pub-2017-63",
    title: "Well-Posedness for General Parametric Quasi-Variational Inclusion Problems",
    authors: "Wangkeeree, R., Anh, L.Q., & Boonman, P.",
    journal: "Optimization, Vol. 66, No. 1, pp. 93–111",
    date: "2017",
    featured: false,
  },
  {
    id: "pub-2016-64",
    title: "A Characterization of Nonemptiness and Boundedness of the Solution Set for Set-Valued Vector Equilibrium Problems via Scalarization and Stability Results",
    authors: "Preechasilp, P. & Wangkeeree, R.",
    journal: "SpringerPlus, Vol. 5, No. 1, pp. 1345",
    date: "2016",
    featured: false,
  },
  {
    id: "pub-2016-65",
    title: "Semicontinuity and Closedness of Parametric Generalized Lexicographic Quasiequilibrium Problems",
    authors: "Wangkeeree, R., Bantaojai, T., & Yimmuang, P.",
    journal: "Journal of Inequalities and Applications, Vol. 2016, No. 1, pp. 1–14",
    date: "2016",
    featured: false,
  },
  {
    id: "pub-2016-66",
    title: "A New General Iterative Methods for Solving the Equilibrium Problems, Variational Inequality Problems and Fixed Point Problems of Nonexpansive Mappings",
    authors: "Thailert, E., Wangkeeree, R., & Preechasilp, P.",
    journal: "Thai Journal of Mathematics, Vol. 14, No. 1, pp. 53–67",
    date: "2016",
    featured: false,
  },
  {
    id: "pub-2016-67",
    title: "A Note on Strict Feasibility and Solvability for Pseudomonotone Equilibrium Problems",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Journal of Nonlinear Science and Applications, Vol. 9, No. 11, pp. 5894–5899",
    date: "2016",
    featured: false,
  },
  {
    id: "pub-2016-68",
    title: "Well-Posedness by Perturbations for the Hemivariational Inequality Governed by a Multi-Valued Map Perturbed with a Nonlinear Term",
    authors: "Wangkeeree, R. & Yimmuang, P.",
    journal: "Pacific Journal of Optimization, Vol. 12, No. 1, pp. 119–131",
    date: "2016",
    featured: false,
  },
  {
    id: "pub-2015-69",
    title: "Well-Posedness for Lexicographic Vector Quasiequilibrium Problems with Lexicographic Equilibrium Constraints",
    authors: "Wangkeeree, R., Bantaojai, T., & Yimmuang, P.",
    journal: "Journal of Inequalities and Applications, Vol. 2015, No. 1",
    date: "2015",
    featured: false,
  },
  {
    id: "pub-2015-70",
    title: "Levitin-Polyak Well-Posedness for Parametric Generalized Quasivariational Inequality Problem of The Minty Type",
    authors: "Wangkeeree, R. & Yimmuang, P.",
    journal: "Journal of Nonlinear and Convex Analysis, Vol. 16, No. 12, pp. 2365–2400",
    date: "2015",
    featured: false,
  },
  {
    id: "pub-2015-71",
    title: "Δ-Convergence for Generalized Hybrid Mappings in CAT(0) Spaces",
    authors: "Wangkeeree, R.",
    journal: "Bulletin of the Malaysian Mathematical Sciences Society, Vol. 38, No. 3, pp. 1041–1064",
    date: "2015",
    link: "https://doi.org/10.1007/s40840-014-0073-1",
    featured: false,
  },
  {
    id: "pub-2015-72",
    title: "Some Proximally Coincidence Points for Non-Self Mappings and Self Mappings in Partially Ordered Metric Spaces",
    authors: "Wangkeeree, R. & Sisarat, N.",
    journal: "Thai Journal of Mathematics, Vol. 13, No. 3, pp. 613–625",
    date: "2015",
    featured: false,
  },
  {
    id: "pub-2015-73",
    title: "Viscosity Approximation Methods for Asymptotically Nonexpansive Mappings in CAT(0) Spaces",
    authors: "Wangkeeree, R., Boonkong, U., & Preechasilp, P.",
    journal: "Fixed Point Theory and Applications, Vol. 2015",
    date: "2015",
    featured: false,
  },
  {
    id: "pub-2014-74",
    title: "A Note on Continuity of Solution Set for Parametric Weak Vector Equilibrium Problems",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Abstract and Applied Analysis, Vol. 2014",
    date: "2014",
    featured: false,
  },
  {
    id: "pub-2014-75",
    title: "Strong and Δ-Convergence of Moudafi’s Iterative Scheme in CAT(0) Spaces",
    authors: "Wangkeeree, R.",
    journal: "Journal of Nonlinear and Convex Analysis, Vol. 16, No. 1, pp. 1–12",
    date: "2014",
    featured: false,
  },
  {
    id: "pub-2014-76",
    title: "On the Hölder Continuity of Solution Maps to Parametric Generalized Vector Quasi-Equilibrium Problems via Nonlinear Scalarization",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Journal of Inequalities and Applications, Vol. 2014",
    date: "2014",
    featured: false,
  },
  {
    id: "pub-2014-77",
    title: "Lower Semicontinuity of Approximate Solution Mappings for Parametric Generalized Vector Equilibrium Problems",
    authors: "Wangkeeree, R., Boonman, P., & Preechasilp, P.",
    journal: "Journal of Inequalities and Applications, Vol. 2014",
    date: "2014",
    featured: false,
  },
  {
    id: "pub-2014-78",
    title: "A Hybrid Subgradient Algorithm for Finding a Common Solution of an Equilibrium Problem and a Family of Strict Pseudocontraction Mappings",
    authors: "Thailert, E., Wangkeeree, R., & Khantree, C.",
    journal: "Journal of Applied Mathematics, Vol. 2014, pp. 8",
    date: "2014",
    featured: false,
  },
  {
    id: "pub-2014-79",
    title: "Continuity of the Solution Mappings to Parametric Generalized Vector Equilibrium Problems",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Applied Mathematics Letters, Vol. 29, pp. 42–45",
    date: "2014",
    featured: false,
  },
  {
    id: "pub-2014-80",
    title: "A General Iterative Method for Multi-Valued Mappings",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Bulletin of the Malaysian Mathematical Sciences Society, Vol. 37, No. 3, pp. 689–701",
    date: "2014",
    featured: false,
  },
  {
    id: "pub-2013-81",
    title: "Iterative Approximation Methods for Mixed Equilibrium Problems for a Countable Family of Quasi-Asymptotically Nonexpansive Multivalued Mappings in Banach Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Fixed Point Theory and Applications, Vol. 2013",
    date: "2013",
    featured: false,
  },
  {
    id: "pub-2013-82",
    title: "The Modified General Iterative Methods for Asymptotically Nonexpansive Semigroups in Banach Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Journal of Inequalities and Applications, Vol. 2013",
    date: "2013",
    featured: false,
  },
  {
    id: "pub-2013-83",
    title: "Viscosity Approximation Methods for Nonexpansive Mappings in CAT(0) Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Journal of Inequalities and Applications, Vol. 2013",
    date: "2013",
    link: "https://doi.org/10.1186/1029-242X-2013-93",
    featured: false,
  },
  {
    id: "pub-2013-84",
    title: "Generalized Nonlinear Vector Mixed Quasi-Variational-Like Inequality Governed by a Multi-Valued Map",
    authors: "Wangkeeree, R. & Yimmuang, P.",
    journal: "Journal of Inequalities and Applications, Vol. 2013",
    date: "2013",
    featured: false,
  },
  {
    id: "pub-2013-85",
    title: "Existence and Iterative Approximation Methods for Generalized Mixed Vector Equilibrium Problems with Relaxed Monotone Mappings",
    authors: "Wangkeeree, R. & Yimmuang, P.",
    journal: "Journal of Applied Mathematics, Vol. 2013, pp. 11",
    date: "2013",
    featured: false,
  },
  {
    id: "pub-2013-86",
    title: "A General Iterative Method for Two Maximal Monotone Operators and 2-Generalized Hybrid Mappings in Hilbert Spaces",
    authors: "Wangkeeree, R. & Boonkong, U.",
    journal: "Fixed Point Theory and Applications, Vol. 2013",
    date: "2013",
    featured: false,
  },
  {
    id: "pub-2013-87",
    title: "The General Iterative Methods for Asymptotically Nonexpansive Semigroups in Banach Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Abstract and Applied Analysis, Vol. 2012, pp. 20",
    date: "2013",
    link: "https://doi.org/10.1155/2012/695183",
    featured: false,
  },
  {
    id: "pub-2013-88",
    title: "Existence Theorems and Iterative Approximation Methods for Generalized Mixed Equilibrium Problems for a Countable Family of Nonexpansive Mappings",
    authors: "Wangkeeree, R. & Kamraksa, U.",
    journal: "Journal of Global Optimization, Vol. 54, pp. 27–46",
    date: "2013",
    link: "https://doi.org/10.1007/s10898-011-9739-5",
    featured: false,
  },
  {
    id: "pub-2013-89",
    title: "Existence and Strong Convergence Theorems for Generalized Mixed Equilibrium Problems of a Finite Family of Asymptotically Nonexpansive Mappings in Banach Spaces",
    authors: "Wangkeeree, R., Dehghan, H., & Preechasilp, P.",
    journal: "Journal of Applied Mathematics, Vol. 2012, pp. 21",
    date: "2013",
    link: "https://doi.org/10.1155/2012/859492",
    featured: false,
  },
  {
    id: "pub-2013-90",
    title: "Modified Noor Iterations for Nonexpansive Semigroups with Generalized Contraction in Banach Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Journal of Inequalities and Applications, Vol. 2012",
    date: "2013",
    featured: false,
  },
  {
    id: "pub-2013-91",
    title: "Iterative Algorithms for Pseudocontraction Semigroups in Banach Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Thai Journal of Mathematics, Vol. 10, No. 1, pp. 59–73",
    date: "2013",
    featured: false,
  },
  {
    id: "pub-2013-92",
    title: "The General Iterative Methods for Nonexpansive Semigroups in Banach Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Journal of Global Optimization",
    date: "2013",
    link: "https://doi.org/10.1007/s10898-011-9835-6",
    featured: false,
  },
  {
    id: "pub-2013-93",
    title: "A New Iterative Scheme for Solving the Equilibrium Problems, Variational Inequality Problems, and Fixed Point Problems in Hilbert Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Journal of Applied Mathematics, Vol. 2012, pp. 21",
    date: "2013",
    link: "https://doi.org/10.1155/2012/154968",
    featured: false,
  },
  {
    id: "pub-2013-94",
    title: "New Generalized Mixed Equilibrium Problem with Respect to Relaxed Semi-Monotone Mappings in Banach Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Journal of Applied Mathematics, Vol. 2012, pp. 25",
    date: "2013",
    link: "https://doi.org/10.1155/2012/790592",
    featured: false,
  },
  {
    id: "pub-2013-95",
    title: "The System of Mixed Equilibrium Problems for Quasi-Nonexpansive Mappings in Hilbert Spaces",
    authors: "Wangkeeree, R. & Boonman, P.",
    journal: "Journal of Applied Mathematics, Vol. 2012, pp. 17",
    date: "2013",
    link: "https://doi.org/10.1155/2012/282094",
    featured: false,
  },
  {
    id: "pub-2013-96",
    title: "Viscosity Approximations by the Shrinking Projection Method of Quasi-Nonexpansive Mappings for Generalized Equilibrium Problems",
    authors: "Wangkeeree, R. & Nimana, N.",
    journal: "Journal of Applied Mathematics, Vol. 2012, pp. 30",
    date: "2013",
    link: "https://doi.org/10.1155/2012/235474",
    featured: false,
  },
  {
    id: "pub-2013-97",
    title: "Existence and Algorithms for the Bilevel New Generalized Mixed Equilibrium Problems in Banach Spaces",
    authors: "Wangkeeree, R. & Yimmuang, P.",
    journal: "Applied Mathematics and Computation, Vol. 219, pp. 3022–3038",
    date: "2013",
    featured: false,
  },
  {
    id: "pub-2013-98",
    title: "Coupled Fixed Point Theorems for Generalized Contractive Mappings in Partially Ordered G-Metric Spaces",
    authors: "Wangkeeree, R. & Bantaojai, T.",
    journal: "Fixed Point Theory and Applications, Vol. 2012",
    date: "2013",
    featured: false,
  },
  {
    id: "pub-2013-99",
    title: "Iterative Algorithms with Perturbations for Solving the Systems of Generalized Equilibrium Problems and the Fixed Point Problems of Two Quasinonexpansive Mappings",
    authors: "Wangkeeree, R. & Boonkong, U.",
    journal: "Abstract and Applied Analysis, Vol. 2012, pp. 22",
    date: "2013",
    link: "https://doi.org/10.1155/2012/161897",
    featured: false,
  },
  {
    id: "pub-2011-100",
    title: "Existence Theorems of the Hemivariational Inequality Governed by a Multi-Valued Map Perturbed with a Nonlinear Term in Banach Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Journal of Global Optimization",
    date: "2011",
    link: "https://doi.org/10.1007/s10898-012-0018-x",
    featured: false,
  },
  {
    id: "pub-2011-101",
    title: "The Modified General Iterative Methods for Nonexpansive Semigroups in Banach Spaces",
    authors: "Wangkeeree, R. & Preechasilp, P.",
    journal: "Fixed Point Theory and Applications, Vol. 2011",
    date: "2011",
    featured: false,
  },
  {
    id: "pub-2011-102",
    title: "Existence and Iterative Approximation of Solutions of Generalized Mixed Quasi-Variational-Like Inequality Problem in Banach Spaces",
    authors: "Kumam, P., Petrot, N., & Wangkeeree, R.",
    journal: "Applied Mathematics and Computation, Vol. 217, No. 18, pp. 7496–7503",
    date: "2011",
    featured: false,
  },
  {
    id: "pub-2011-103",
    title: "General Composite Algorithms for Solving General Equilibrium Problems and Fixed Point Problems in Hilbert Spaces",
    authors: "Wangkeeree, R. & Bantaojai, T.",
    journal: "Thai Journal of Mathematics, Vol. 9, No. 1, pp. 191–212",
    date: "2011",
    featured: false,
  },
  {
    id: "pub-2011-104",
    title: "A General Composite Algorithms for Solving General Equilibrium Problems and Fixed Point Problems in Hilbert Spaces",
    authors: "Wangkeeree, R., Kamraksa, U., & Wangkeeree, R.",
    journal: "Abstract and Applied Analysis, Vol. 2011, pp. 25",
    date: "2011",
    featured: false,
  },
  {
    id: "pub-2011-105",
    title: "Existence and Iterative Approximation for Generalized Equilibrium Problems for a Countable Family of Nonexpansive Mappings in Banach Spaces",
    authors: "Kamraksa, U. & Wangkeeree, R.",
    journal: "Fixed Point Theory and Applications, Vol. 2011",
    date: "2011",
    featured: false,
  },
  {
    id: "pub-2011-106",
    title: "A Viscosity Approximation Method of Common Solutions for Quasi-Variational Inclusion and Fixed Point Problems",
    authors: "Kumam, P., Petrot, N., & Wangkeeree, R.",
    journal: "Fixed Point Theory, Vol. 12, No. 1, pp. 165–178",
    date: "2011",
    featured: false,
  },
  {
    id: "pub-2011-107",
    title: "Convergence Theorem for Mixed Equilibrium Problems and Variational Inequality Problems for Relaxed Cocoercive Mappings",
    authors: "Wangkeeree, R., Petrot, N., Kumam, P., & Jaiboon, C.",
    journal: "Journal of Computational Analysis and Applications, Vol. 13, No. 3, pp. 425–449",
    date: "2011",
    featured: false,
  },
  {
    id: "pub-2011-108",
    title: "The General Hybrid Approximation Methods for Nonexpansive Mappings in Banach Spaces",
    authors: "Wangkeeree, R.",
    journal: "Abstract and Applied Analysis, Vol. 2011, pp. 19",
    date: "2011",
    link: "https://doi.org/10.1155/2011/854360",
    featured: false,
  },
  {
    id: "pub-2011-109",
    title: "Generalized Equilibrium Problems and Fixed Point Problems for Nonexpansive Semigroups in Hilbert Spaces",
    authors: "Kamraksa, U. & Wangkeeree, R.",
    journal: "Journal of Global Optimization",
    date: "2011",
    link: "https://doi.org/10.1007/s10898-011-9654-9",
    featured: false,
  },
  {
    id: "pub-2011-110",
    title: "New Iterative Approximation Methods for a Countable Family of Nonexpansive Mappings in Banach Spaces",
    authors: "Nammanee, K. & Wangkeeree, R.",
    journal: "Fixed Point Theory and Applications, Vol. 2011, pp. 24",
    date: "2011",
    link: "https://doi.org/10.1155/2011/671754",
    featured: false,
  },
  {
    id: "pub-2011-111",
    title: "The General Iterative Methods for Nonexpansive Mappings in Banach Spaces",
    authors: "Wangkeeree, R., Petrot, N., & Wangkeeree, R.",
    journal: "Journal of Global Optimization",
    date: "2011",
    link: "https://doi.org/10.1007/s10898-010-9617-6",
    featured: false,
  },
  {
    id: "pub-2010-112",
    title: "A General Iterative Scheme for Strict Pseudononspreading Mapping Related to Optimization Problem in Hilbert Spaces",
    authors: "Petrot, N. & Wangkeeree, R.",
    journal: "Journal of Nonlinear Analysis and Optimization, Vol. 2, No. 2, pp. 329–336",
    date: "2010",
    featured: false,
  },
  {
    id: "pub-2010-113",
    title: "Strong Convergence Theorems of Viscosity Iterative Methods for a Countable Family of Strict Pseudo-Contractions in Banach Spaces",
    authors: "Kamraksa, U. & Wangkeeree, R.",
    journal: "Fixed Point Theory and Applications, Vol. 2010, pp. 21",
    date: "2010",
    link: "https://doi.org/10.1155/2010/579725",
    featured: false,
  },
  {
    id: "pub-2010-114",
    title: "A Hybrid Iterative Scheme for Variational Inequality Problems for Finite Families of Relatively Weak Quasi-Nonexpansive Mappings",
    authors: "Kamraksa, U. & Wangkeeree, R.",
    journal: "Journal of Inequalities and Applications, Vol. 2010, pp. 23",
    date: "2010",
    link: "https://doi.org/10.1155/2010/724851",
    featured: false,
  },
  {
    id: "pub-2010-115",
    title: "Convergence Theorems Based on the Shrinking Projection Method for Variational Inequality and Equilibrium Problems",
    authors: "Kamraksa, U. & Wangkeeree, R.",
    journal: "Journal of Applied Mathematics and Computing",
    date: "2010",
    link: "https://doi.org/10.1007/s12190-010-0427-2",
    featured: false,
  },
  {
    id: "pub-2010-116",
    title: "An Iterative Method for Solving the Generalized System of Relaxed Cocoercive Quasivariational Inclusions and Fixed Point Problems of an Infinite Family of Strictly Pseudocontractive Mappings",
    authors: "Tianchai, P. & Wangkeeree, R.",
    journal: "The International Journal of Mathematics and Mathematical Sciences, Vol. 2010",
    date: "2010",
    featured: false,
  },
  {
    id: "pub-2010-117",
    title: "The Shrinking Projection Method for Generalized Mixed Equilibrium Problems and Fixed Point Problems in Banach Spaces",
    authors: "Markshoe, P., Wangkeeree, R., & Kamraksa, U.",
    journal: "Journal of Nonlinear Analysis and Optimization, Vol. 1, No. 1, pp. 111–129",
    date: "2010",
    featured: false,
  },
  {
    id: "pub-2010-118",
    title: "A New Hybrid Method for Solving Generalized Equilibrium Problem and Common Fixed Points of Asymptotically Quasi Nonexpansive Mappings in Banach Spaces",
    authors: "Kamraksa, U. & Wangkeeree, R.",
    journal: "Journal of Nonlinear Analysis and Optimization, Vol. 1, No. 1, pp. 55–69",
    date: "2010",
    featured: false,
  },
  {
    id: "pub-2009-119",
    title: "A General Iterative Process for Solving a System of Variational Inclusions in Banach Spaces",
    authors: "Kamraksa, U. & Wangkeeree, R.",
    journal: "Journal of Inequalities and Applications, Vol. 2010, pp. 24",
    date: "2009",
    link: "https://doi.org/10.1155/2010/190126",
    featured: false,
  },
  {
    id: "pub-2009-120",
    title: "The Shrinking Projection Method for Solving Variational Inequality Problems and Fixed Point Problems in Banach Spaces",
    authors: "Wangkeeree, R. & Wangkeeree, R.",
    journal: "Abstract and Applied Analysis, Vol. 2009, pp. 26",
    date: "2009",
    link: "https://doi.org/10.1155/2009/624798",
    featured: false,
  },
  {
    id: "pub-2009-121",
    title: "A Hybrid Iterative Scheme for Equilibrium Problems and Fixed Point Problems of Asymptotically k-Strict Pseudo Contractions",
    authors: "Kumam, P., Petrot, N., & Wangkeeree, R.",
    journal: "Journal of Computational and Applied Mathematics, Vol. 233, No. 1, pp. 183–194",
    date: "2009",
    link: "https://doi.org/10.1016/j.cam.2009.09.036",
    featured: false,
  },
  {
    id: "pub-2009-122",
    title: "A General Iterative Method for Variational Inequality Problems, Mixed Equilibrium Problems and Fixed Point Problems of Strictly Pseudocontractive Mappings in Hilbert Spaces",
    authors: "Wangkeeree, R. & Wangkeeree, R.",
    journal: "Fixed Point Theory and Applications, Vol. 2009, pp. 32",
    date: "2009",
    link: "https://doi.org/10.1155/2009/519065",
    featured: false,
  },
  {
    id: "pub-2009-123",
    title: "Strong Convergence of the Iterative Scheme Based on the Extragradient Method for Mixed Equilibrium Problems and Fixed Point Problems of an Infinite Family of Nonexpansive Mappings",
    authors: "Wangkeeree, R. & Wangkeeree, R.",
    journal: "Nonlinear Analysis: Hybrid Systems, Vol. 3, pp. 615–630",
    date: "2009",
    link: "https://doi.org/10.1016/j.nahs.2009.06.009",
    featured: false,
  },
  {
    id: "pub-2009-124",
    title: "General Cesaro Mean Approximation Methods for Nonexpansive Mappings in Hilbert Space",
    authors: "Markshoe, P. & Wangkeeree, R.",
    journal: "Thai Journal of Mathematics, Vol. 7, No. 1, pp. 35–47",
    date: "2009",
    featured: false,
  },
  {
    id: "pub-2009-125",
    title: "An Iterative Approximation Method for Solving a General System of Variational Inequality Problems and Mixed Equilibrium Problems",
    authors: "Wangkeeree, R. & Kamraksa, U.",
    journal: "Nonlinear Analysis: Hybrid Systems, Vol. 3, pp. 615–630",
    date: "2009",
    featured: false,
  },
  {
    id: "pub-2009-126",
    title: "A General Iterative Method for Solving the Variational Inequality Problem and Fixed Point Problem of an Infinite Family of Nonexpansive Mappings in Hilbert Spaces",
    authors: "Wangkeeree, R. & Kamraksa, U.",
    journal: "Fixed Point Theory and Applications, Vol. 2009, pp. 23",
    date: "2009",
    featured: false,
  },
  {
    id: "pub-2009-127",
    title: "A General Approximation Method for Nonexpansive Semigroups in Hilbert Spaces",
    authors: "Wangkeeree, R.",
    journal: "The Far East Journal of Applied Mathematics, Vol. 34, No. 2, pp. 221–232",
    date: "2009",
    featured: false,
  },
  {
    id: "pub-2009-128",
    title: "Strong Convergence Theorems for Equilibrium Problems and Fixed Point Problems of a Countable Family for Nonexpansive Mappings",
    authors: "Wangkeeree, R., Jaiboon, C., & Kumam, P.",
    journal: "The International Journal of Applied Mathematics and Mechanics, Vol. 1, No. 1, pp. 1–17",
    date: "2009",
    featured: false,
  },
  {
    id: "pub-2009-129",
    title: "An Iterative Approximation Method for a Countable Family of Nonexpansive Mappings in Hilbert Spaces",
    authors: "Wangkeeree, R.",
    journal: "Bulletin of the Malaysian Mathematical Sciences Society, Vol. 32, No. 3, pp. 313–326",
    date: "2009",
    featured: false,
  },
  {
    id: "pub-2009-130",
    title: "Strong Convergence of Averaging Iterations of Nonexpansive Nonself-Mappings in Banach Spaces",
    authors: "Wangkeeree, R.",
    journal: "International Mathematical Forum, Vol. 4, No. 14, pp. 687–696",
    date: "2009",
    featured: false,
  },
  {
    id: "pub-2009-131",
    title: "Some Modified Extragradient Approximation Methods for Variational Inequality Problems and Equilibrium Problems of Nonexpansive Mappings",
    authors: "Wangkeeree, R. & Kamraksa, U.",
    journal: "Applied Mathematical Sciences, Vol. 3, No. 14, pp. 653–666",
    date: "2009",
    featured: false,
  },
  {
    id: "pub-2008-132",
    title: "An Extragradient Approximation Method for Fixed Point Problems of a Countable Family of Nonexpansive Mappings",
    authors: "Wangkeeree, R. & Markshoe, P.",
    journal: "Far East Journal of Mathematical Sciences (FJMS), Vol. 30, No. 3, pp. 473–488",
    date: "2008",
    featured: false,
  },
  {
    id: "pub-2008-133",
    title: "A General Iterative Method for Variational Inequality Problems and Fixed Point Problems of an Infinite Family of Nonexpansive Mappings in Hilbert Spaces",
    authors: "Wangkeeree, R. & Kamraksa, U.",
    journal: "Thai Journal of Mathematics, Vol. 6, No. 1, pp. 147–170",
    date: "2008",
    featured: false,
  },
  {
    id: "pub-2008-134",
    title: "An Extragradient Approximation Method for Equilibrium Problems and Fixed Point Problems of a Countable Family of Nonexpansive Mappings",
    authors: "Wangkeeree, R.",
    journal: "Fixed Point Theory and Applications, Vol. 2008, pp. 17",
    date: "2008",
    link: "https://doi.org/10.1155/2008/134148",
    featured: false,
  },
  {
    id: "pub-2008-135",
    title: "Viscosity Approximative Methods for Nonexpansive Nonself-Mappings Without Boundary Conditions in Banach Spaces",
    authors: "Wangkeeree, R. & Markshoe, P.",
    journal: "Applied Mathematical Sciences, Vol. 2, No. 22, pp. 1053–1062",
    date: "2008",
    featured: false,
  },
  {
    id: "pub-2008-136",
    title: "Viscosity Approximative Methods to Cesaro Mean Iterations for Nonexpansive Nonself-Mappings in Banach Spaces",
    authors: "Wangkeeree, R.",
    journal: "Applied Mathematics and Computation, Vol. 201, pp. 239–249",
    date: "2008",
    featured: false,
  },
  {
    id: "pub-2007-137",
    title: "Implicit Iterations Process for a Finite Family of Nonexpansive Nonself-Mappings in Banach Spaces",
    authors: "Wangkeeree, R.",
    journal: "International Journal of Mathematical Sciences and Applications (IJMSA), Vol. 1, No. 1, pp. 1–12",
    date: "2007",
    featured: false,
  },
  {
    id: "pub-2007-138",
    title: "Strong Convergence of Cesaro Mean Iterations for Nonexpansive Nonself-Mappings in Banach Spaces",
    authors: "Wangkeeree, R.",
    journal: "Fixed Point Theory and Applications, Vol. 2007, pp. 11",
    date: "2007",
    link: "https://doi.org/10.1155/2007/59262",
    featured: false,
  },
  {
    id: "pub-2007-139",
    title: "Strong Convergence Theorems of Viscosity Averaging Sequences for Asymptotically Nonexpansive Nonself-Mappings",
    authors: "Plubtieng, S. & Wangkeeree, R.",
    journal: "The Far East Journal of Mathematical Sciences, Vol. 27, No. 2, pp. 483–496",
    date: "2007",
    featured: false,
  },
  {
    id: "pub-2007-140",
    title: "Implicit Iterations of Two Finite Families for Nonexpansive Mappings in Banach Spaces",
    authors: "Plubtieng, S., Wangkeeree, R., & Ungchittrakool, K.",
    journal: "Numerical Functional Analysis and Optimization, Vol. 28, No. 5-6, pp. 737–749",
    date: "2007",
    featured: false,
  },
  {
    id: "pub-2007-141",
    title: "Approximation of Common Random Fixed Point for a Finite Family of Random Operators",
    authors: "Plubtieng, S., Kumam, P., & Wangkeeree, R.",
    journal: "International Journal of Mathematics and Mathematical Sciences, Vol. 2007, pp. 12",
    date: "2007",
    link: "https://doi.org/10.1155/2007/69626",
    featured: false,
  },
  {
    id: "pub-2007-142",
    title: "Random Three-Step Iteration Scheme and Common Random Fixed Point of Three Operators",
    authors: "Plubtieng, S., Kumam, P., & Wangkeeree, R.",
    journal: "Journal of Applied Mathematics and Stochastic Analysis, Vol. 2007, pp. 10",
    date: "2007",
    link: "https://doi.org/10.1155/2007/82517",
    featured: false,
  },
  {
    id: "pub-2007-143",
    title: "Viscosity Approximation Methods for Nonexpansive Nonself-Mappings in Hilbert Spaces",
    authors: "Wangkeeree, R.",
    journal: "International Journal of Mathematics and Mathematical Sciences, Vol. 2007, pp. 10",
    date: "2007",
    link: "https://doi.org/10.1155/2007/48648",
    featured: false,
  },
  {
    id: "pub-2006-144",
    title: "Moudafi’s Viscosity Approximations for Lipschitzian Mappings in Banach Spaces",
    authors: "Plubtieng, S., Suzuki, T., & Wangkeeree, R.",
    journal: "Proceedings of the International Symposium on Banach and Function Spaces II, pp. 1–9",
    date: "2006",
    featured: false,
  },
  {
    id: "pub-2006-145",
    title: "Noor Iterations with Errors for Non-Lipschitzian Mappings in Banach Spaces",
    authors: "Plubtieng, S. & Wangkeeree, R.",
    journal: "Kyungpook Mathematical Journal, Vol. 46, pp. 201–209",
    date: "2006",
    featured: false,
  },
  {
    id: "pub-2006-146",
    title: "On the Convergence of Modified Noor Iterations with Errors for Asymptotically Nonexpansive Mappings",
    authors: "Plubtieng, S., Wangkeeree, R., & Punpaeng, R.",
    journal: "Journal of Mathematical Analysis and Applications, Vol. 322, pp. 1018–1029",
    date: "2006",
    featured: false,
  },
  {
    id: "pub-2006-147",
    title: "Strong Convergence Theorems for Three Step Iterations with Errors for Non-Lipschitzian Nonself-Mappings in Banach Spaces",
    authors: "Plubtieng, S. & Wangkeeree, R.",
    journal: "Computers and Mathematics with Applications, Vol. 51, pp. 1093–1102",
    date: "2006",
    featured: false,
  },
  {
    id: "pub-2006-148",
    title: "Strong Convergence Theorems for Multi-Step Iterations with Errors in Banach Spaces",
    authors: "Plubtieng, S. & Wangkeeree, R.",
    journal: "Journal of Mathematical Analysis and Applications, Vol. 321, pp. 10–23",
    date: "2006",
    featured: false,
  },
  {
    id: "pub-2005-149",
    title: "Noor Iterations with Error for Non-Lipschitzian Mappings in Banach Spaces",
    authors: "Plubtieng, S. & Wangkeeree, R.",
    journal: "Proceedings of International Conference on Nonlinear Analysis and Convex Analysis (Okinawa), pp. 1–8",
    date: "2005",
    featured: false,
  },
  {
    id: "pub-2005-150",
    title: "Strong Convergence Theorems for Asymptotically Nonexpansive Nonself-Mappings",
    authors: "Plubtieng, S. & Wangkeeree, R.",
    journal: "Thai Journal of Mathematics, Vol. 3, No. 1, pp. 1–11",
    date: "2005",
    featured: false,
  },
  {
    id: "pub-2005-151",
    title: "Fixed Point Iteration for Asymptotically Quasi-Nonexpansive Mappings in Banach Spaces",
    authors: "Plubtieng, S. & Wangkeeree, R.",
    journal: "International Journal of Mathematics and Mathematical Sciences, Vol. 2005, No. 11, pp. 1685–1692",
    date: "2005",
    featured: false,
  },
  {
    id: "pub-2004-152",
    title: "Strong Convergence Theorems of Three Step Iterations with Errors for Asymptotically Quasi-Nonexpansive Nonself-Mappings in Banach Spaces",
    authors: "Wangkeeree, R.",
    journal: "Thai Journal of Mathematics, Vol. 2, pp. 283–294",
    date: "2004",
    featured: false,
  },
  {
    id: "pub-2003-153",
    title: "On Property k-NUC in Cesaro-Musielak-Orlicz Sequence Spaces",
    authors: "Wangkeeree, R.",
    journal: "Thai Journal of Mathematics, Vol. 1, pp. 119–130",
    date: "2003",
    featured: false,
  },
];

export const newsData: News[] = [
  {
    id: "news-voices-2026",
    slug: "voices-global-research-community-2026",
    title: "Workshop/Seminar: Voices from the Global Research Community — Inspiration and Experience",
    date: "2026-05-13",
    category: "Workshop",
    featuredImage: getImageUrl("/images/news/voices-global-research-2026/group.jpg"),
    content: "The Department of Mathematics, Faculty of Science, Naresuan University hosted the workshop 'Voices from the Global Research Community: Inspiration and Experience' on May 13, 2026. The event featured Professor Dr. Poom Kumam, an International Researcher & Distinguished Scholar recognized as the Top Mathematician in Thailand, as the keynote speaker. The seminar provided students, researchers, and academics with valuable insights into international research experiences, inspiration, and new perspectives on academic research. Organized under the DeepMathAI Frontier Research and Innovation Cluster at Room SC2-112, Department of Mathematics, Faculty of Science, Naresuan University.",
    gallery: [
      getImageUrl("/images/news/voices-global-research-2026/group.jpg"),
      getImageUrl("/images/news/voices-global-research-2026/seminar_room.jpg"),
      getImageUrl("/images/news/voices-global-research-2026/audience.jpg"),
      getImageUrl("/images/news/voices-global-research-2026/presentation.jpg"),
      getImageUrl("/images/news/voices-global-research-2026/poster.jpg")
    ],
    featured: true,
  },
  {
    id: "news-1",
    slug: "icoml-2026-keynote",
    title: "Invited Keynote at ICOML 2026",
    date: "2026-06-15",
    category: "Conference",
    featuredImage: getImageUrl("/images/seminars/cantho2026_1.jpg"),
    content: "Prof. Rabian Wangkeeree delivered a keynote speech at the International Conference on Optimization and Machine Learning (ICOML) 2026. The talk focused on novel approaches in solving Support Vector Machines with Epigraph Reformulated Generalized Pinball Loss Function.",
    gallery: [
      getImageUrl("/images/seminars/cantho2026_1.jpg"),
      getImageUrl("/images/seminars/cantho2026_2.jpg"),
      getImageUrl("/images/seminars/cantho2026_3.jpg")
    ],
    featured: true,
  },
  {
    id: "news-2",
    slug: "new-publication-cam-2026",
    title: "New Publication in Journal of Computational and Applied Mathematics",
    date: "2026-04-10",
    category: "Research",
    featuredImage: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&q=80&w=800",
    content: "Our recent paper titled 'Neurodynamical Neural Network Method for Solving Support Vector Machines with Epigraph Reformulated Generalized Pinball Loss Function' has been accepted and published in the prestigious Journal of Computational and Applied Mathematics (Elsevier).",
    featured: false,
  },
];

export const seminarsData: Seminar[] = [
  {
    id: "sem-1",
    title: "A Neurodynamical Neural Network Approach for Solving Support Vector Machine Problems with Insensitive Zone Pinball Loss via Hyperbolic Tangent Smoothing Technique",
    location: "School of Education, Can Tho University, Vietnam",
    date: "February 23-27, 2026",
  },
  {
    id: "sem-2",
    title: "Pattern Data Classification via Noise-Insensitive Loss in Support Vector Machines",
    location: "Pukyong National University, South Korea",
    date: "October 13-19, 2024",
  },
  {
    id: "sem-3",
    title: "The Regularized Stochastic Nesterov's Accelerated Quasi-Newton Method",
    location: "Optimization Workshop, National Taiwan Normal University",
    date: "August 18-22, 2024",
  },
];

export const conferencesData: Conference[] = [
  {
    "id": "conf-2005-1",
    "title": "Noor Iterations with Errors for Nonlipschitzian Mapping in Banach Spaces",
    "description": "The Fourth International Conference on Nonlinear Analysis and Convex Analysis (NACA 2005), Okinawa Convention Center, Okinawa, Japan, June 30 - July 4, 2005 (with Prof. Somyot Plubtieng)",
    "location": "See description",
    "date": "2005",
    "featured": false
  },
  {
    "id": "conf-2005-2",
    "title": "Strong Convergence Theorems for Multi-step Noor Iterations with Errors in Banach Spaces",
    "description": "International Conference on Fixed Point Theory and its Applications, Guanajuato, Mexico, July 17-23, 2005 (with Prof. Somyot Plubtieng)",
    "location": "See description",
    "date": "2005",
    "featured": false
  },
  {
    "id": "conf-2006-3",
    "title": "Viscosity Approximation Methods for Nonexpansive Nonself-Mappings in Hilbert Spaces",
    "description": "The Second International Symposium on Banach and Function Spaces 2006 (ISBFS2006), Kyushu Institute of Technology (KIT), Tobata Campus, Kitakyushu, Japan, September 13-18, 2006",
    "location": "See description",
    "date": "2006",
    "featured": false
  },
  {
    "id": "conf-2007-4",
    "title": "Approximation of Common Fixed Points of a Countable Family of Nonexpansive Mappings in Banach Spaces",
    "description": "The Fifth International Conference on Nonlinear Analysis and Convex Analysis (NACA 2007), National Tsing-Hua University, Hsinchu, Taiwan, May 31 - June 4, 2007",
    "location": "See description",
    "date": "2007",
    "featured": false
  },
  {
    "id": "conf-2007-5",
    "title": "Viscosity Approximative Methods to Cesaro Mean Iterations for Nonexpansive Nonself-Mappings in Banach Spaces",
    "description": "The 8th International Conference on Fixed Point Theory and its Applications, Chiang Mai, Thailand, July 16-22, 2007",
    "location": "See description",
    "date": "2007",
    "featured": false
  },
  {
    "id": "conf-2009-6",
    "title": "A Hybrid Iterative Scheme for Equilibrium Problems and Fixed Point Problems of Asymptotically K-Strictly Pseudo-Contractions",
    "description": "The Sixth International Conference on Nonlinear Analysis and Convex Analysis (NACA 2009), Tokyo Institute of Technology, Tokyo, Japan, March 27-31, 2009",
    "location": "See description",
    "date": "2009",
    "featured": false
  },
  {
    "id": "conf-2009-7",
    "title": "A General Iterative Method for Variational Inequality Problems, Mixed Equilibrium Problems, and Fixed Point Problems of Strictly Pseudocontractive Mappings in Hilbert Spaces",
    "description": "Function Spaces 2009, Jagiellonian University, Department of Mathematics and Computer Science, Krakow, Poland, July 6-11, 2009",
    "location": "See description",
    "date": "2009",
    "featured": false
  },
  {
    "id": "conf-2009-8",
    "title": "A General Iterative Method for Variational Inequality Problems, Mixed Equilibrium Problems, and Fixed Point Problems of Strictly Pseudocontractive Mappings in Hilbert Spaces",
    "description": "The 10th International Conference on Nonlinear Functional Analysis and Applications, Masan and Chinju, Korea, July 27-31, 2009",
    "location": "See description",
    "date": "2009",
    "featured": false
  },
  {
    "id": "conf-2009-9",
    "title": "The System of Variational Inequalities and Fixed Point Problems for a Countable Family of Strict Pseudo-Contractions in Banach Spaces",
    "description": "The 4th International Conference on Fixed Point Theory, Variational Inequality and its Approximation Algorithms, China, July 16-19, 2009",
    "location": "See description",
    "date": "2009",
    "featured": false
  },
  {
    "id": "conf-2010-10",
    "title": "A General Iterative Method for the System of Variational Inequalities of a Countable Family of Strict Pseudo-Contractions",
    "description": "The Second Asian Conference on Nonlinear Analysis and Optimization, Royal Paradise Hotel Spa, Patong Beach, Phuket, Thailand, September 9-12, 2010",
    "location": "See description",
    "date": "2010",
    "featured": false
  },
  {
    "id": "conf-2011-11",
    "title": "Convergence Theorems of Iterative Algorithms for Pseudocontraction Semigroups in Banach Spaces",
    "description": "The 5th Conference On Fixed Point Theory And Applications (CFPTA 2011), Lampang Rajabhat University, Thailand, July 8-9, 2011",
    "location": "See description",
    "date": "2011",
    "featured": false
  },
  {
    "id": "conf-2011-12",
    "title": "The General Hybrid Approximation Methods for Nonexpansive Mappings in Banach Spaces",
    "description": "The Seventh International Conference on Nonlinear Analysis and Convex Analysis (NACA 2011), Pukyong National University (PKNU), Busan, Republic of Korea, August 2-5, 2011",
    "location": "See description",
    "date": "2011",
    "featured": false
  },
  {
    "id": "conf-2012-13",
    "title": "A Solution for the Generalized-Hemivariational Inequality Problems",
    "description": "International Conference on Nonlinear Analysis and Optimization: Theory, Algorithms and Applications in Science and Engineering, Tianjin Polytechnic University and Civil Aviation University of China, Tianjin, China, August 13-15, 2012",
    "location": "See description",
    "date": "2012",
    "featured": false
  },
  {
    "id": "conf-2012-14",
    "title": "Existence Theorem of the Ky Fan-Hemivariational Inequality Problems in Banach Spaces",
    "description": "The 6th International Conference on Fixed Point Theory and Applications, Faculty of Science, Uttaradit Rajabhat University, Uttaradit, Thailand, July 31 - August 1, 2012",
    "location": "See description",
    "date": "2012",
    "featured": false
  },
  {
    "id": "conf-2012-15",
    "title": "Existence Theorems of the Generalized Variational-Hemivariational Inequalities",
    "description": "The International Conference 2012 on Mathematical Inequalities and Nonlinear Functional Analysis with Applications (MINAA 2012), Gyeongsang National University, Chinju, South Korea",
    "location": "See description",
    "date": "2012",
    "featured": false
  },
  {
    "id": "conf-2013-16",
    "title": "An Iterative Method for Generalized Mixed Vector Equilibrium Problem with a Relaxed Monotone Mapping and a Countable Family of Nonexpansive Mappings in a Hilbert Space",
    "description": "Spring School: Analysis and Approximation in Optimization Under Uncertainty, Vietnam National Foundation for Science and Technology Development, University of Science and Technology, Hanoi, Vietnam, February 18-23, 2013",
    "location": "See description",
    "date": "2013",
    "featured": false
  },
  {
    "id": "conf-2013-17",
    "title": "Hölder Calmness of Solutions to Parametric Weak Generalized Ky Fan Inequality",
    "description": "The 7th Asian Conference on Fixed Point Theory and Optimization (ACFPTO 2013), Kasetsart University, Kamphaeng Saen Campus, Thailand, July 18-20, 2013",
    "location": "See description",
    "date": "2013",
    "featured": false
  },
  {
    "id": "conf-2013-18",
    "title": "Hölder Calmness of Solutions to Parametric Weak Generalized Ky Fan Inequality",
    "description": "The 8th International Conference on Nonlinear Analysis and Convex Analysis (NACA 2013), Hirosaki University, Hirosaki, Aomori, Japan, August 2-6, 2013",
    "location": "See description",
    "date": "2013",
    "featured": false
  },
  {
    "id": "conf-2014-19",
    "title": "Semi-Continuity of Parametric Generalized Lexicographic Quasiequilibrium Problems",
    "description": "The Fourth Asian Conference on Nonlinear Analysis and Optimization, National Taiwan Normal University, Taipei, Taiwan, August 5-9, 2014",
    "location": "See description",
    "date": "2014",
    "featured": false
  },
  {
    "id": "conf-2014-20",
    "title": "Hadamard Well-Posedness and Levitin-Polyak-Well-Posedness of a Generalized Equilibrium Problem in Banach Space",
    "description": "The 8th Asian Conference on Fixed Point Theory and Optimization (ACFPTO 2014), Faculty of Science, Naresuan University, Thailand, July 28-30, 2014",
    "location": "See description",
    "date": "2014",
    "featured": false
  },
  {
    "id": "conf-2014-21",
    "title": "Well-Posedness for the Bilevel New Generalized Mixed Equilibrium Problems in Banach Spaces",
    "description": "The 20th Conference of the International Federation of Operational Research Societies, Barcelona, Spain, July 13-18, 2014",
    "location": "See description",
    "date": "2014",
    "featured": false
  },
  {
    "id": "conf-2015-22",
    "title": "Well-Posedness for Parametric Generalized Quasi-Variational Inclusion Problems",
    "description": "The 17th British-French-German Conference on Optimization, London, United Kingdom, June 15-17, 2015",
    "location": "See description",
    "date": "2015",
    "featured": false
  },
  {
    "id": "conf-2015-23",
    "title": "Hölder Continuity of Solution Maps of Parametric Ky Fan Inequalities in Metric Linear Spaces",
    "description": "World Conference on Global Optimization 2015 (WCGO 2015), Hilton University of Florida Conference Centre, Gainesville, Florida, USA, February 22-25, 2015",
    "location": "See description",
    "date": "2015",
    "featured": false
  },
  {
    "id": "conf-2015-24",
    "title": "Hölder Continuity of Solution Maps of Parametric Equilibrium Problems",
    "description": "The 9th International Conference on Nonlinear Analysis and Convex Analysis, Rimkok Resort Hotel, Chiang Rai, Thailand, January 21-25, 2015",
    "location": "See description",
    "date": "2015",
    "featured": false
  },
  {
    "id": "conf-2016-25",
    "title": "Sequential Optimality Conditions for Infinite Fractional Programming Problem with DC Functions",
    "description": "The 9th Asian Conference on Fixed Point Theory and Optimization (ACFPTO 2016), King Mongkut’s University of Technology, Bangkok, Thailand, May 18-20, 2016",
    "location": "See description",
    "date": "2016",
    "featured": false
  },
  {
    "id": "conf-2016-26",
    "title": "Hölder Continuity of Solution Maps to Parametric Primal and Dual Weak Generalized Ky Fan Inequalities",
    "description": "NAO-Asia 2016, Niigata, Japan, August 1-6, 2016",
    "location": "See description",
    "date": "2016",
    "featured": false
  },
  {
    "id": "conf-2016-27",
    "title": "On Optimality Theorems for Multiobjective Convex Optimization Problems Over Feasible Sets Defined by Tangentially Convex Inequalities",
    "description": "ICCOPT 2016, Tokyo, Japan, August 6-11, 2016",
    "location": "See description",
    "date": "2016",
    "featured": false
  },
  {
    "id": "conf-2017-28",
    "title": "Characterizing Robust Weak Sharp Solution Sets of Uncertain Convex Optimization Problems",
    "description": "International Workshop on Optimization Algorithms and Some Related Problems, Hanoi, Vietnam, December 14-16, 2017",
    "location": "See description",
    "date": "2017",
    "featured": false
  },
  {
    "id": "conf-2018-29",
    "title": "Characterizations of Solution Sets of Convex Optimization Problems Without Convex Representation",
    "description": "The 10th Asian Conference on Fixed Point Theory and Optimizations, The Empress Hotel, Chiang Mai, Thailand, July 16-18, 2018",
    "location": "See description",
    "date": "2018",
    "featured": false
  },
  {
    "id": "conf-2018-30",
    "title": "Characterizing Robust Weak Sharp Solution Sets of Uncertain Convex Optimizations",
    "description": "The 6th Asian Conference on Nonlinear Analysis and Optimization, Okinawa Institute of Science and Technology Graduate University ANA Intercontinental Manza Beach Resort, Okinawa, Japan, November 5-9, 2018",
    "location": "See description",
    "date": "2018",
    "featured": false
  },
  {
    "id": "conf-2019-31",
    "title": "Data Classification by Using Smooth Generalized Pinball Loss Functions in Support Vector Machine",
    "description": "IMLIS 2019, National Dong Hwa University (NDHU), Taiwan, November 19-22, 2019",
    "location": "See description",
    "date": "2019",
    "featured": false
  },
  {
    "id": "conf-2022-32",
    "title": "A new technique for Pneumonia infected patients image recognition based on combinatorial algorithm of smooth generalized pinball SVM and VAEs",
    "description": "Computational and Mathematical Methods in Science and Engineering (CMMSE2022), Rota, Cádiz, Spain, July 3-7, 2022",
    "location": "See description",
    "date": "2022",
    "featured": false
  },
  {
    "id": "conf-2023-33",
    "title": "Image classification using Linex Least Square Twin bounded Support Vector Machine",
    "description": "International Conference on Optimization and Variational Analysis with Application 2023 (ICOVAA-2023), Hanoi, Vietnam, July 10-15, 2023",
    "location": "See description",
    "date": "2023",
    "featured": false
  },
  {
    "id": "conf-2023-34",
    "title": "Image classification using Linex Least Square Twin bounded Support Vector Machine",
    "description": "IWOTAA 2023, Saigon University, Ho chi minh, Vietnam, July 17 - 18, 2023",
    "location": "See description",
    "date": "2023",
    "featured": false
  },
  {
    "id": "conf-2024-35",
    "title": "Stability of solutions to multiobjective optimization and related problems",
    "description": "VIASM, Hanoi, Vietnam, March 17-24, 2024 (with Prof. Lam Quoc Anh)",
    "location": "See description",
    "date": "2024",
    "featured": false
  },
  {
    "id": "conf-2024-36",
    "title": "The regularized stochastic Nesterov’s accelerated quasi-Newton method for nonconvex optimization",
    "description": "Computational and Mathematical Methods in Science and Engineering (CMMSE2024), Rota, Cádiz, Spain, July 2-8, 2024",
    "location": "See description",
    "date": "2024",
    "featured": false
  },
  {
    "id": "conf-2024-37",
    "title": "Pattern Data Classification via Noise-insensitive Loss in Support Vector Machines (SVMs)",
    "description": "International Conference on Applied Mathematics (ICAM 2024), Ton Duc Thung University, Ho Chi Minh, Vietnam, July 11-13, 2024",
    "location": "See description",
    "date": "2024",
    "featured": false
  },
  {
    "id": "conf-2024-38",
    "title": "The Regularized Stochastic Nesterov's Accelerated Quasi-Newton Method with Applications",
    "description": "2024 Optimization Workshop, College of Science, National Taiwan Normal University, August 18–22, 2024",
    "location": "See description",
    "date": "2024",
    "featured": false
  },
  {
    "id": "conf-2024-39",
    "title": "Pattern Data Classification via Noise-Insensitive Loss in Support Vector Machines (SVMs)",
    "description": "Pukyong National University, South Korea, October 13–19, 2024",
    "location": "See description",
    "date": "2024",
    "featured": false
  },
  {
    "id": "conf-2025-40",
    "title": "Regularized Nesterov's Accelerated Damped BFGS Method for Stochastic Optimization",
    "description": "The 12th Asian Conference on Fixed Point Theory and Optimization 2025, Duangtawan Hotel, Chiang Mai, Thailand, January 15–18, 2025",
    "location": "See description",
    "date": "2025",
    "featured": false
  },
  {
    "id": "conf-2025-41",
    "title": "Enhancing Automated Glaucoma Prediction with Multi-View Deep Learning and Image Inpainting on Retinal Fundus Images",
    "description": "Joint Conferences CMMSE 2025 and HPC 2025, Hotel Barceló, Rota, Cádiz, Spain, July 7–13, 2025",
    "location": "See description",
    "date": "2025",
    "featured": false
  },
  {
    "id": "conf-2025-42",
    "title": "Deep Learning-Based Retinal Image Analysis for Glaucoma Using Multi-View Features and Vascular Inpainting",
    "description": "The 14th International Conference on Pure and Applied Mathematics (ICPAM 2025), Rome, Italy, July 15–18, 2025",
    "location": "See description",
    "date": "2025",
    "featured": false
  },
  {
    "id": "conf-2025-43",
    "title": "Support Vector Machines with Rescaled Generalized Pinball Loss for Enhanced Classification Performance",
    "description": "The Asian Mathematical Conference (AMC 2025), Chiang Mai University, Chiang Mai, Thailand, August 3–7, 2025",
    "location": "See description",
    "date": "2025",
    "featured": false
  }
];

export const achievementsData: Achievement[] = [
  {
    "id": "ach-2013-1",
    "title": "Thesis Advisor Award (Good Level)",
    "description": "the National Research Council of Thailand (NRCT)",
    "level": "2013"
  },
  {
    "id": "ach-2013-2",
    "title": "Outstanding Researcher in Academic Research",
    "description": "Naresuan University",
    "level": "2013"
  },
  {
    "id": "ach-2014-3",
    "title": "Outstanding Personnel (Academic)",
    "description": "Naresuan University",
    "level": "2014"
  },
  {
    "id": "ach-2014-4",
    "title": "Director of the Center of Excellence in Mathematics Research",
    "description": "",
    "level": "2014"
  },
  {
    "id": "ach-2015-5",
    "title": "Outstanding Personnel and Outstanding Alumni",
    "description": "Faculty of Science, Naresuan University",
    "level": "2015"
  },
  {
    "id": "ach-2016-6",
    "title": "Outstanding Researcher in Academic Research",
    "description": "Naresuan University",
    "level": "2016"
  },
  {
    "id": "ach-2017-7",
    "title": "Mid-Career Researcher Development Grant",
    "description": "the Thailand Research Fund (TRF)",
    "level": "2017"
  },
  {
    "id": "ach-2018-8",
    "title": "Appointed as Professor by Royal Command",
    "description": "",
    "level": "2018"
  },
  {
    "id": "ach-2021-9",
    "title": "Advanced and Basic Research Promotion Grant",
    "description": "the Program Management Unit for Human Resources \& Institutional Development, Research and Innovation (PMU-B)",
    "level": "2021"
  },
  {
    "id": "ach-2022-10",
    "title": "Outstanding Researcher Award for Published Works",
    "description": "1st FARE Project, Faculty of Science, Naresuan University",
    "level": "2022"
  }
];

export const galleryData: GalleryAlbum[] = [
  {
    id: "gal-1",
    title: "Conference Presentations 2025",
    coverImage: getImageUrl("/images/seminars/cantho2026_1.jpg"),
    images: [
      getImageUrl("/images/seminars/cantho2026_1.jpg"),
      getImageUrl("/images/seminars/cantho2026_2.jpg"),
      getImageUrl("/images/seminars/cantho2026_3.jpg")
    ],
    date: "2025",
  },
  {
    id: "gal-2",
    title: "Research Center Team",
    coverImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=400",
    images: [
      "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=800",
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=800",
    ],
    date: "2024",
  },
];

export const collaboratorsData: Collaborator[] = [
  {
    id: "col-1",
    name: "Prof. Lam Quoc Anh",
    institution: "Can Tho University, Vietnam",
    role: "Research Collaborator",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=150",
  },
  {
    id: "col-2",
    name: "Dr. Yonas A. Belay",
    institution: "Naresuan University, Thailand",
    role: "Postdoctoral Researcher",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150",
  },
  {
    id: "col-3",
    name: "S. Suppalap",
    institution: "Naresuan University, Thailand",
    role: "Ph.D. Student",
    avatarUrl: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=150",
  },
];

export const contactData: ContactInfo = {
  address: [
    "Department of Mathematics, Faculty of Science",
    "Naresuan University",
    "Phitsanulok 65000, Thailand"
  ],
  email: "rabianw@nu.ac.th",
  phone: "+66 55 963249",
  journals: [
    { name: "Mathematical Methods in the Applied Sciences", url: "https://onlinelibrary.wiley.com/page/journal/10991476/homepage/editorialboard.html" },
    { name: "Nonlinear Analysis: Modelling and Control", url: "https://www.journals.vu.lt/nonlinear-analysis" },
    { name: "Journal of Nonlinear and Variational Analysis", url: "https://jnva.biemdas.com/" },
    { name: "Carpathian Journal of Mathematics", url: "https://www.carpathian.cunbm.utcluj.ro/" },
    { name: "Journal of Computational and Applied Mathematics", url: "https://www.sciencedirect.com/journal/journal-of-computational-and-applied-mathematics" },
    { name: "The Journal of Supercomputing", url: "https://link.springer.com/journal/11227" },
    { name: "Applied Sciences", url: "https://www.mdpi.com/journal/applsci" },
  ]
};
